spring:
  application:
    name: springBoot-training-test-01
  datasource:
    username: root
    password: root
    url: jdbc:mysql://localhost:3306/springBoot-training-test-01
    driver-class-name  : com.mysql.cj.jdbc.Driver
  sql:
    init:
      mode: always
server:
  servlet:
    context-path: /api